// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc1
// source: api/audio.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	AudioService_Upload_FullMethodName = "/audio.AudioService/Upload"
)

type AudioServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadRequest, StatusResponse], error)
}

type audioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioServiceClient(cc grpc.ClientConnInterface) AudioServiceClient {
	return &audioServiceClient{cc}
}

func (c *audioServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadRequest, StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioService_ServiceDesc.Streams[0], AudioService_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadRequest, StatusResponse]{ClientStream: stream}
	return x, nil
}

type AudioService_UploadClient = grpc.BidiStreamingClient[UploadRequest, StatusResponse]

type AudioServiceServer interface {
	Upload(grpc.BidiStreamingServer[UploadRequest, StatusResponse]) error
	mustEmbedUnimplementedAudioServiceServer()
}

type UnimplementedAudioServiceServer struct{}

func (UnimplementedAudioServiceServer) Upload(grpc.BidiStreamingServer[UploadRequest, StatusResponse]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedAudioServiceServer) mustEmbedUnimplementedAudioServiceServer() {}
func (UnimplementedAudioServiceServer) testEmbeddedByValue()                      {}

type UnsafeAudioServiceServer interface {
	mustEmbedUnimplementedAudioServiceServer()
}

func RegisterAudioServiceServer(s grpc.ServiceRegistrar, srv AudioServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioService_ServiceDesc, srv)
}

func _AudioService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioServiceServer).Upload(&grpc.GenericServerStream[UploadRequest, StatusResponse]{ServerStream: stream})
}

type AudioService_UploadServer = grpc.BidiStreamingServer[UploadRequest, StatusResponse]

var AudioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio.AudioService",
	HandlerType: (*AudioServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _AudioService_Upload_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/audio.proto",
}