// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: api/audio.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      int32                  `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	Codec         string                 `protobuf:"bytes,4,opt,name=codec,proto3" json:"codec,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalSize     int64                  `protobuf:"varint,6,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioMetadata) Reset() {
	*x = AudioMetadata{}
	mi := &file_api_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioMetadata) ProtoMessage() {}

func (x *AudioMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AudioMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AudioMetadata) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioMetadata) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioMetadata) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *AudioMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AudioMetadata) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	IsLast        bool                   `protobuf:"varint,2,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	Sequence      int32                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_api_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *AudioChunk) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Message       isUploadRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_api_audio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_audio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadRequest) GetMessage() isUploadRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *UploadRequest) GetMetadata() *AudioMetadata {
	if x != nil {
		if x, ok := x.Message.(*UploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() *AudioChunk {
	if x != nil {
		if x, ok := x.Message.(*UploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadRequest_Message interface {
	isUploadRequest_Message()
}

type UploadRequest_Metadata struct {
	Metadata *AudioMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadRequest_Chunk struct {
	Chunk *AudioChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadRequest_Metadata) isUploadRequest_Message() {}

func (*UploadRequest_Chunk) isUploadRequest_Message() {}

type ProcessingStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ReceivedBytes  int64                  `protobuf:"varint,2,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"`
	ChunkCount     int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Progress       float64                `protobuf:"fixed64,6,opt,name=progress,proto3" json:"progress,omitempty"`
	ProcessedBytes int64                  `protobuf:"varint,7,opt,name=processed_bytes,json=processedBytes,proto3" json:"processed_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessingStatus) Reset() {
	*x = ProcessingStatus{}
	mi := &file_api_audio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingStatus) ProtoMessage() {}

func (x *ProcessingStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_audio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessingStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProcessingStatus) GetReceivedBytes() int64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

func (x *ProcessingStatus) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *ProcessingStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessingStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProcessingStatus) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProcessingStatus) GetProcessedBytes() int64 {
	if x != nil {
		return x.ProcessedBytes
	}
	return 0
}

type ProcessingSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ReceivedBytes int64                  `protobuf:"varint,2,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	OutputFormat  string                 `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	SampleRate    int32                  `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      int32                  `protobuf:"varint,6,opt,name=channels,proto3" json:"channels,omitempty"`
	FrameSize     int32                  `protobuf:"varint,7,opt,name=frame_size,json=frameSize,proto3" json:"frame_size,omitempty"`
	FrameCount    int32                  `protobuf:"varint,8,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	DurationMs    int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	AvgEnergy     float64                `protobuf:"fixed64,10,opt,name=avg_energy,json=avgEnergy,proto3" json:"avg_energy,omitempty"`
	MaxEnergy     float64                `protobuf:"fixed64,11,opt,name=max_energy,json=maxEnergy,proto3" json:"max_energy,omitempty"`
	MinEnergy     float64                `protobuf:"fixed64,12,opt,name=min_energy,json=minEnergy,proto3" json:"min_energy,omitempty"`
	OutputFile    string                 `protobuf:"bytes,13,opt,name=output_file,json=outputFile,proto3" json:"output_file,omitempty"`
	Status        string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingSummary) Reset() {
	*x = ProcessingSummary{}
	mi := &file_api_audio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingSummary) ProtoMessage() {}

func (x *ProcessingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_audio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessingSummary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProcessingSummary) GetReceivedBytes() int64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

func (x *ProcessingSummary) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *ProcessingSummary) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *ProcessingSummary) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *ProcessingSummary) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *ProcessingSummary) GetFrameSize() int32 {
	if x != nil {
		return x.FrameSize
	}
	return 0
}

func (x *ProcessingSummary) GetFrameCount() int32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *ProcessingSummary) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ProcessingSummary) GetAvgEnergy() float64 {
	if x != nil {
		return x.AvgEnergy
	}
	return 0
}

func (x *ProcessingSummary) GetMaxEnergy() float64 {
	if x != nil {
		return x.MaxEnergy
	}
	return 0
}

func (x *ProcessingSummary) GetMinEnergy() float64 {
	if x != nil {
		return x.MinEnergy
	}
	return 0
}

func (x *ProcessingSummary) GetOutputFile() string {
	if x != nil {
		return x.OutputFile
	}
	return ""
}

func (x *ProcessingSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessingSummary) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Message       isStatusResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_audio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_audio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatusResponse) GetMessage() isStatusResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StatusResponse) GetStatus() *ProcessingStatus {
	if x != nil {
		if x, ok := x.Message.(*StatusResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *StatusResponse) GetSummary() *ProcessingSummary {
	if x != nil {
		if x, ok := x.Message.(*StatusResponse_Summary); ok {
			return x.Summary
		}
	}
	return nil
}

type isStatusResponse_Message interface {
	isStatusResponse_Message()
}

type StatusResponse_Status struct {
	Status *ProcessingStatus `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type StatusResponse_Summary struct {
	Summary *ProcessingSummary `protobuf:"bytes,2,opt,name=summary,proto3,oneof"`
}

func (*StatusResponse_Status) isStatusResponse_Message() {}

func (*StatusResponse_Summary) isStatusResponse_Message() {}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_audio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_audio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_audio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_audio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_api_audio_proto protoreflect.FileDescriptor

const file_api_audio_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/audio.proto\x12\x05audio\"\xbc\x01\n" +
	"\rAudioMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\x05R\bchannels\x12\x14\n" +
	"\x05codec\x18\x04 \x01(\tR\x05codec\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"total_size\x18\x06 \x01(\x03R\ttotalSize\"U\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x02 \x01(\bR\x06isLast\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x05R\bsequence\"y\n" +
	"\rUploadRequest\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.audio.AudioMetadataH\x00R\bmetadata\x12)\n" +
	"\x05chunk\x18\x02 \x01(\v2\x11.audio.AudioChunkH\x00R\x05chunkB\t\n" +
	"\amessage\"\xec\x01\n" +
	"\x10ProcessingStatus\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0ereceived_bytes\x18\x02 \x01(\x03R\rreceivedBytes\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x01R\bprogress\x12'\n" +
	"\x0fprocessed_bytes\x18\a \x01(\x03R\x0eprocessedBytes\"\xe9\x03\n" +
	"\x11ProcessingSummary\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0ereceived_bytes\x18\x02 \x01(\x03R\rreceivedBytes\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\x12#\n" +
	"\routput_format\x18\x04 \x01(\tR\foutputFormat\x12\x1f\n" +
	"\vsample_rate\x18\x05 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x06 \x01(\x05R\bchannels\x12\x1d\n" +
	"\n" +
	"frame_size\x18\a \x01(\x05R\tframeSize\x12\x1f\n" +
	"\vframe_count\x18\b \x01(\x05R\n" +
	"frameCount\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"avg_energy\x18\n" +
	" \x01(\x01R\tavgEnergy\x12\x1d\n" +
	"\n" +
	"max_energy\x18\v \x01(\x01R\tmaxEnergy\x12\x1d\n" +
	"\n" +
	"min_energy\x18\f \x01(\x01R\tminEnergy\x12\x1f\n" +
	"\voutput_file\x18\r \x01(\tR\n" +
	"outputFile\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\"\x84\x01\n" +
	"\x0eStatusResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x17.audio.ProcessingStatusH\x00R\x06status\x124\n" +
	"\asummary\x18\x02 \x01(\v2\x18.audio.ProcessingSummaryH\x00R\asummaryB\t\n" +
	"\amessage\")\n" +
	"\rHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"i\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds2I\n" +
	"\fAudioService\x129\n" +
	"\x06Upload\x12\x14.audio.UploadRequest\x1a\x15.audio.StatusResponse(\x010\x01B\aZ\x05./apib\x06proto3"

var (
	file_api_audio_proto_rawDescOnce sync.Once
	file_api_audio_proto_rawDescData []byte
)

func file_api_audio_proto_rawDescGZIP() []byte {
	file_api_audio_proto_rawDescOnce.Do(func() {
		file_api_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_audio_proto_rawDesc), len(file_api_audio_proto_rawDesc)))
	})
	return file_api_audio_proto_rawDescData
}

var file_api_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_audio_proto_goTypes = []any{
	(*AudioMetadata)(nil),
	(*AudioChunk)(nil),
	(*UploadRequest)(nil),
	(*ProcessingStatus)(nil),
	(*ProcessingSummary)(nil),
	(*StatusResponse)(nil),
	(*HealthRequest)(nil),
	(*HealthResponse)(nil),
}
var file_api_audio_proto_depIdxs = []int32{
	0,
	1,
	3,
	4,
	2,
	5,
	5,
	4,
	4,
	4,
	0,
}

func init() { file_api_audio_proto_init() }
func file_api_audio_proto_init() {
	if File_api_audio_proto != nil {
		return
	}
	file_api_audio_proto_msgTypes[2].OneofWrappers = []any{
		(*UploadRequest_Metadata)(nil),
		(*UploadRequest_Chunk)(nil),
	}
	file_api_audio_proto_msgTypes[5].OneofWrappers = []any{
		(*StatusResponse_Status)(nil),
		(*StatusResponse_Summary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_audio_proto_rawDesc), len(file_api_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_audio_proto_goTypes,
		DependencyIndexes: file_api_audio_proto_depIdxs,
		MessageInfos:      file_api_audio_proto_msgTypes,
	}.Build()
	File_api_audio_proto = out.File
	file_api_audio_proto_goTypes = nil
	file_api_audio_proto_depIdxs = nil
}